language: python
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_6a37b794cca0_key -iv $encrypted_6a37b794cca0_iv
  -in test/env.ini.enc -out test/env.ini -d
install:
- pip3 install -r requirements.txt
script:
- coverage run --source=Misskey setup.py test
after_success:
- coveralls
