language: python
python:
- 3.7
before_install:
- sudo apt-get update
- sudo apt-get install -y libyaml-dev
- pip3 install pipenv --upgrade-strategy=only-if-needed
install:
- pipenv --python 3
- pipenv sync --dev
script:
- pipenv run test
after_success:
- pipenv run reporttest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: gqxQi7RGZOunmk4NRR9KBjFoLVE21mmd+Nsiku7yrpIilJ5fmtvqtmiMPTsLSvrYRuKCiVx83mOrKMT8Uaq9GMiUv/s9srfXrpV6UVc5xrXry+SPbxCRPn5p/qcglf2HyoPJSrWxEnQe2PnmZQf99kpeHoXXa4Y/CJz6ir61ud9bSLAnscoEmyV3pdfzfsLil85wHsjR7nGl4jOPByKdKBQu8FAcADcqu0hsJUAoubnmGNG7ckad6/IY8k/l0JlOXjZiA47y1dEvkZLYZOHHgycX38XLR/FreqvpEe5OWfKPUXJILas2UyMJE519pwDgr6PfBh3ZwrD5uvVvGWEjucp9sq73FQDY+dADLlTz1BVGICeA8AUF85M2pxDg3iqj9yTGDIS22od+IhhLFAnTZoB2zpzJtPC7aBTDqVuTrVFP/ZZWTCToWx3DcH9CUCCg37muSyPtEcwu4q+23MHKx2SmHlXaxhZ1vJdQ3C7lt9dCT2FoQAXpEdo0sHOI20AOGpebCkBGoQPlMgpRLFKRFeoy9cy6CUbyJMmdjcc0R3tKsesrmMK8KKHDKwklVheiU+oIAlRkNjwrCmBxKtaYPW4irmwpWGVEN3hcCJWjONiZH+OnLjPpKp5g4CNqd9ajX/RbDsuUKUd30SVJkabMe29hQ/z7BfuSReRBnKN2Hns=
  on:
    tags: true
  distributions: "bdist_wheel"
