language: python
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_4a1a76f876b7_key -iv $encrypted_4a1a76f876b7_iv
  -in test/env.ini.enc -out test/env.ini -d
install:
- pip3 install -r requirements.txt
script:
- coverage run --source=Misskey setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: gqxQi7RGZOunmk4NRR9KBjFoLVE21mmd+Nsiku7yrpIilJ5fmtvqtmiMPTsLSvrYRuKCiVx83mOrKMT8Uaq9GMiUv/s9srfXrpV6UVc5xrXry+SPbxCRPn5p/qcglf2HyoPJSrWxEnQe2PnmZQf99kpeHoXXa4Y/CJz6ir61ud9bSLAnscoEmyV3pdfzfsLil85wHsjR7nGl4jOPByKdKBQu8FAcADcqu0hsJUAoubnmGNG7ckad6/IY8k/l0JlOXjZiA47y1dEvkZLYZOHHgycX38XLR/FreqvpEe5OWfKPUXJILas2UyMJE519pwDgr6PfBh3ZwrD5uvVvGWEjucp9sq73FQDY+dADLlTz1BVGICeA8AUF85M2pxDg3iqj9yTGDIS22od+IhhLFAnTZoB2zpzJtPC7aBTDqVuTrVFP/ZZWTCToWx3DcH9CUCCg37muSyPtEcwu4q+23MHKx2SmHlXaxhZ1vJdQ3C7lt9dCT2FoQAXpEdo0sHOI20AOGpebCkBGoQPlMgpRLFKRFeoy9cy6CUbyJMmdjcc0R3tKsesrmMK8KKHDKwklVheiU+oIAlRkNjwrCmBxKtaYPW4irmwpWGVEN3hcCJWjONiZH+OnLjPpKp5g4CNqd9ajX/RbDsuUKUd30SVJkabMe29hQ/z7BfuSReRBnKN2Hns=
  on:
    tags: true
