name: Lint
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Install project dependencies
        run: |
          poetry install --sync --only=main,dev
      - name: Run lint
        run: |
          poetry run flake8
